-- ---------------------------------------------------------
-- USERS
-- ---------------------------------------------------------
CREATE TABLE users (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50)  NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    full_name     VARCHAR2(100) NOT NULL,
    email         VARCHAR2(100) UNIQUE,
    role          VARCHAR2(20)  DEFAULT 'LIBRARIAN' NOT NULL
                      CHECK (role IN ('ADMIN', 'LIBRARIAN')),
    active        NUMBER(1)     DEFAULT 1 NOT NULL
                      CHECK (active IN (0, 1)),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- CATEGORIES
-- ---------------------------------------------------------
CREATE TABLE categories (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL UNIQUE,
    description CLOB,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- BOOKS
-- ---------------------------------------------------------
CREATE TABLE books (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR2(20)  UNIQUE,
    title            VARCHAR2(255) NOT NULL,
    author           VARCHAR2(255) NOT NULL,
    publisher        VARCHAR2(255),
    publish_year     NUMBER,
    category_id      NUMBER,
    total_copies     NUMBER DEFAULT 1 NOT NULL,
    available_copies NUMBER DEFAULT 1 NOT NULL,
    description      CLOB,
    cover_image_path VARCHAR2(500),
    deleted          NUMBER(1) DEFAULT 0 NOT NULL
                         CHECK (deleted IN (0, 1)),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_book_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id) ON DELETE SET NULL,

    CONSTRAINT chk_copies
        CHECK (available_copies >= 0 AND available_copies <= total_copies)
);

CREATE INDEX idx_books_title    ON books(title);
CREATE INDEX idx_books_author   ON books(author);
CREATE INDEX idx_books_category ON books(category_id);

-- ---------------------------------------------------------
-- MEMBERS
-- ---------------------------------------------------------
CREATE TABLE members (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code VARCHAR2(20)  NOT NULL UNIQUE,
    full_name   VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) UNIQUE,
    phone       VARCHAR2(20),
    address     CLOB,
    join_date   DATE      DEFAULT CURRENT_DATE NOT NULL,
    expiry_date DATE      NOT NULL,
    status      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
                    CHECK (status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED')),
    deleted     NUMBER(1) DEFAULT 0 NOT NULL
                    CHECK (deleted IN (0, 1)),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Đảm bảo ngày hết hạn phải sau ngày tham gia
    CONSTRAINT chk_expiry CHECK (expiry_date > join_date)
);

CREATE INDEX idx_members_code ON members(member_code);
CREATE INDEX idx_members_name ON members(full_name);

-- ---------------------------------------------------------
-- BORROW_RECORDS
-- ---------------------------------------------------------
CREATE TABLE borrow_records (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   NUMBER NOT NULL,
    book_id     NUMBER NOT NULL,
    borrow_date DATE   DEFAULT CURRENT_DATE NOT NULL,
    due_date    DATE   NOT NULL,
    return_date DATE,
    status      VARCHAR2(20) DEFAULT 'BORROWING' NOT NULL
                    CHECK (status IN ('BORROWING', 'RETURNED', 'OVERDUE', 'LOST')),
    notes       CLOB,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_borrow_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_borrow_book
        FOREIGN KEY (book_id)
        REFERENCES books(id),

    -- Nếu status = RETURNED thì return_date phải có giá trị
    CONSTRAINT chk_return_date
        CHECK (
            (status = 'RETURNED' AND return_date IS NOT NULL) OR
            (status <> 'RETURNED')
        ),

    -- due_date phải sau borrow_date
    CONSTRAINT chk_due_date CHECK (due_date > borrow_date)
);

CREATE INDEX idx_borrow_member ON borrow_records(member_id);
CREATE INDEX idx_borrow_book   ON borrow_records(book_id);
CREATE INDEX idx_borrow_status ON borrow_records(status);

-- ---------------------------------------------------------
-- FINES
-- ---------------------------------------------------------
CREATE TABLE fines (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrow_record_id NUMBER        NOT NULL,
    amount           NUMBER(10, 2) DEFAULT 0 NOT NULL,
    reason           VARCHAR2(255),
    paid             NUMBER(1) DEFAULT 0 NOT NULL
                         CHECK (paid IN (0, 1)),
    paid_date        DATE,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fine_borrow
        FOREIGN KEY (borrow_record_id)
        REFERENCES borrow_records(id) ON DELETE CASCADE,

    -- Nếu paid = 1 thì paid_date phải có giá trị
    CONSTRAINT chk_paid_date
        CHECK (
            (paid = 1 AND paid_date IS NOT NULL) OR
            (paid = 0)
        )
);

-- Thêm index cho FK của fines (bị thiếu trong bản gốc)
CREATE INDEX idx_fines_borrow ON fines(borrow_record_id);

-- ---------------------------------------------------------
-- TRIGGERS: tự động cập nhật updated_at
-- ---------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_users_updated
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_books_updated
BEFORE UPDATE ON books
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_members_updated
BEFORE UPDATE ON members
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_borrow_updated
BEFORE UPDATE ON borrow_records
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_fines_updated
BEFORE UPDATE ON fines
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ---------------------------------------------------------
-- TRIGGER: tự động cập nhật status OVERDUE theo due_date
-- Kích hoạt mỗi khi borrow_records được UPDATE
-- (Để chạy định kỳ nên dùng DBMS_SCHEDULER thay cho trigger)
-- ---------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_borrow_overdue
BEFORE UPDATE ON borrow_records
FOR EACH ROW
BEGIN
    IF :NEW.status = 'BORROWING' AND :NEW.due_date < CURRENT_DATE THEN
        :NEW.status := 'OVERDUE';
    END IF;
END;
/